language: go

go:
  - 1.10.x

services:
  - docker

install:
  - go get github.com/mattn/goveralls

after_install:
  - docker-compose up -d

script:
  - go test -v ./...
  - go run main.go
  - go run main.go version
  - $GOPATH/bin/goveralls -service=travis-ci
  
notifications:
  email: false