language: go

go:
  - 1.10.x

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - go test -timeout 240s -v ./
  - go run main.go
  - go run main.go version

after_success:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false