language: go

go:
  - 1.10.x

services:
  - docker

after_install:
  - docker-compose up -d
  - go get github.com/mattn/goveralls

script:
  - go test -v ./...
  - go run main.go
  - go run main.go version

after_success:
  - $GOPATH/bin/goveralls -service=travis-ci

notifications:
  email: false