language: go

go:
  - 1.10.x

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - go test -v ./...
  - go run main.go
  - go run main.go version
  
notifications:
  email: false