language: go

go:
  - 1.10.x

services:
  - docker

install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

after_install:
  - docker-compose up -d

script:
  - go test -v ./...
  - go run main.go
  - go run main.go version
  - goveralls -service=travis-ci
  
notifications:
  email: false